export const products = [
  {
    pic: '/product/C1.jpg',
    title: 'Modern',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '',
  },
  {
    pic: '/product/C2.jpg',
    title: 'Transitional',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '',
  },
  {
    pic: '/product/C3.jpg',
    title: 'AAlam',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/C4.jpg',
    title: 'Transitional',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/C5.jpg',
    title: 'Imara',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/C6.jpg',
    title: 'Unshaped',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/C7.jpg',
    title: 'Solid',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/C8.jpg',
    title: 'Aurora',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
]
