export const products = [
  {
    pic: '/product/product1.webp',
    title: 'Headphone',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '',
  },
  {
    pic: '/product/product1.webp',
    title: 'Headphone',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '',
  },
  {
    pic: '/product/product1.webp',
    title: 'Headphone',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/product1.webp',
    title: 'Headphone',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/product1.webp',
    title: 'Headphone',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/product1.webp',
    title: 'Headphone',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/product1.webp',
    title: 'Headphone',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
  {
    pic: '/product/product1.webp',
    title: 'Headphone',
    disc: '',
    price: '$10',
    rating: '⭐⭐⭐⭐',
    discount: '30%',
  },
]
