'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/app/Header'
import Footer from '@/components/app/Footer'
import Toast from '@/components/ui/TostCantainer'
import { createContext } from 'react'
import { getCookie } from './axios/CookieConfig'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const Context = createContext()
const token = getCookie('access_token')
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Context.Provider value={{}}>
          <Header />
          {children}
          <Footer />
          <Toast />
        </Context.Provider>
      </body>
    </html>
  )
}
